### ISSUE TITLE
Deal with duplicated oem*.inf files somehow

### ISSUE THREAD

**Issue by JustAMan** [JustAMan/pyWinClobber#5]

**Comment by sadshade** [comment]
Nope. 
  
    Reading all OEM drivers... done
    Reading oem*.inf files...
    Traceback (most recent call last):
      File "<string>", line 287, in <module>
      File "<string>", line 237, in main
    Exception: oem39.inf is duplicate of oem37.inf

[oem39.inf.txt](https://github.com/JustAMan/pyWinClobber/files/101034/oem39.inf.txt)
